'use client';

import { useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Info } from 'lucide-react';
import type { LineRow, WellnessAlert } from '~/lib/ultaura/types';
import NavigationMenu from '~/core/ui/Navigation/NavigationMenu';
import NavigationItem from '~/core/ui/Navigation/NavigationItem';
import { WellnessAlertsList } from './WellnessAlertsList';
import { AlertSettings } from './AlertSettings';
import { AlertsLineFilter } from './components/AlertsLineFilter';

const ALERTS_INFO_TIP = (
  <div className="flex items-start gap-3 rounded-lg border border-primary/30 bg-primary/5 px-4 py-3.5">
    <Info className="h-[18px] w-[18px] text-primary flex-shrink-0 mt-0.5" />
    <p className="text-xs text-primary leading-snug">
      These alerts are generated by AI based on conversation patterns and are
      not medical, clinical, or professional advice. Ultaura is not an emergency
      service. If you believe there is immediate danger, contact local emergency
      services (911 in the US).{' '}
      <Link
        href="/docs/safety-and-contacts/wellness-alerts"
        className="text-primary font-medium underline underline-offset-2 hover:no-underline"
      >
        Learn more →
      </Link>
    </p>
  </div>
);

const NOTIFICATIONS_INFO_TIP = (
  <div className="flex items-start gap-3 rounded-lg border border-primary/30 bg-primary/5 px-4 py-3.5">
    <Info className="h-[18px] w-[18px] text-primary flex-shrink-0 mt-0.5" />
    <div className="text-xs text-primary leading-snug space-y-1.5">
      <p>
        All notifications are sent to your billing email and any confirmed{' '}
        <Link
          href="/dashboard/privacy?tab=family&section=recipients"
          className="text-primary font-medium underline underline-offset-2 hover:no-underline"
        >
          family recipients
        </Link>
        .
      </p>
      <ul className="list-disc pl-4 space-y-0.5">
        <li>Weekly summaries and missed call alerts are delivered in full.</li>
        <li>Wellness alerts follow the sharing tier set by your loved one.</li>
      </ul>
    </div>
  </div>
);

type AlertsTabValue = 'wellness-alerts' | 'alert-settings';

const ALERTS_TABS: Array<{
  value: AlertsTabValue;
  label: string;
  path: string;
}> = [
  {
    value: 'wellness-alerts',
    label: 'Wellness Alerts',
    path: '/dashboard/alerts?tab=wellness-alerts',
  },
  {
    value: 'alert-settings',
    label: 'Notifications',
    path: '/dashboard/alerts?tab=alert-settings',
  },
];

interface AlertsPageClientProps {
  alerts: WellnessAlert[];
  lines: LineRow[];
  settings: Parameters<typeof AlertSettings>[0]['settings'];
  deliveryEmail: string;
  disabled?: boolean;
}

export function AlertsPageClient({
  alerts,
  lines,
  settings,
  deliveryEmail,
  disabled,
}: AlertsPageClientProps) {
  const searchParams = useSearchParams();
  const [selectedLineId, setSelectedLineId] = useState('all');

  const tabParam = searchParams.get('tab');
  const activeTab: AlertsTabValue =
    tabParam === 'wellness-alerts' || tabParam === 'alert-settings'
      ? tabParam
      : 'wellness-alerts';

  const filteredAlerts = useMemo(() => {
    if (selectedLineId === 'all') return alerts;
    return alerts.filter((alert) => alert.lineId === selectedLineId);
  }, [alerts, selectedLineId]);

  const filteredSettings = useMemo(() => {
    if (selectedLineId === 'all') return settings;
    return settings.filter((s) => s.line.id === selectedLineId);
  }, [settings, selectedLineId]);

  const lineFilterData = lines.map((l) => ({
    id: l.id,
    display_name: l.display_name,
  }));

  return (
    <div className="space-y-6 pb-12">
      <div className="mb-6">
        {lines.length > 1 && (
          <div className="mb-3 w-full sm:w-[16rem] rounded-xl ring-2 ring-primary">
            <AlertsLineFilter
              lines={lineFilterData}
              value={selectedLineId}
              onValueChange={setSelectedLineId}
            />
          </div>
        )}

        <NavigationMenu bordered scrollable>
          {ALERTS_TABS.map((tab) => (
            <NavigationItem
              key={tab.value}
              active={tab.value === activeTab}
              scroll={false}
              link={{ path: tab.path, label: tab.label }}
            />
          ))}
        </NavigationMenu>
      </div>

      <div className="space-y-4">
        {activeTab === 'wellness-alerts' && (
          <>
            {ALERTS_INFO_TIP}
            <WellnessAlertsList alerts={filteredAlerts} />
          </>
        )}
        {activeTab === 'alert-settings' && (
          <div className="flex min-w-0 flex-1 flex-col gap-6">
            {NOTIFICATIONS_INFO_TIP}
            <AlertSettings
              settings={filteredSettings}
              deliveryEmail={deliveryEmail}
              disabled={disabled}
            />
          </div>
        )}
      </div>
    </div>
  );
}
