packages:
  - 'plugins/chatbot'
  - 'plugins/feedback-popup'
  - 'plugins/cookie-banner'
  - 'packages/*'
  - 'telephony'
  - 'remotion'
onlyBuiltDependencies:
  - cypress
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
