// Tools router - handles Grok tool calls

import { Router } from 'express';
import { setReminderRouter } from './set-reminder.js';
import { scheduleCallRouter } from './schedule-call.js';
import { optOutRouter } from './opt-out.js';
import { forgetMemoryRouter } from './forget-memory.js';
import { markPrivateRouter } from './mark-private.js';
import { storeMemoryRouter } from './store-memory.js';
import { updateMemoryRouter } from './update-memory.js';
import { excludeTopicRouter } from './exclude-topic.js';
import { includeTopicRouter } from './include-topic.js';
import { listExclusionsRouter } from './list-exclusions.js';
import { reviewMemoriesRouter } from './review-memories.js';
import { voiceConsentRouter } from './voice-consent.js';
import { safetyEventRouter } from './safety-event.js';
import { overageActionRouter } from './overage-action.js';
import { requestUpgradeRouter } from './request-upgrade.js';
import { reportConversationLanguageRouter } from './report-conversation-language.js';
import { logCallInsightsRouter } from './log-call-insights.js';
import { setPauseModeRouter } from './set-pause-mode.js';
import { markTopicPrivateRouter } from './mark-topic-private.js';
import { storeCallPreviewRouter } from './store-call-preview.js';
import { markPreviewOutcomeRouter } from './mark-preview-outcome.js';
import { logSegmentEngagementRouter } from './log-segment-engagement.js';
import { manageStoryArcRouter } from './manage-story-arc.js';
import { storeLifeChapterRouter } from './store-life-chapter.js';
import { logMoodSnapshotRouter } from './log-mood-snapshot.js';
import { updateContentPreferenceRouter } from './update-content-preference.js';
import { updateRelationshipRouter } from './update-relationship.js';
import { markRelationshipDeceasedRouter } from './mark-relationship-deceased.js';
import { logCognitiveObservationRouter } from './log-cognitive-observation.js';
import { adjustAccessibilityRouter } from './adjust-accessibility.js';
import { storeMilestoneRouter } from './store-milestone.js';
import { markMilestoneCelebratedRouter } from './mark-milestone-celebrated.js';
import { logHealthMentionRouter } from './log-health-mention.js';
import { skipScheduleRouter } from './skip-schedule.js';
import { snoozeScheduleRouter } from './snooze-schedule.js';
import { rescheduleScheduleRouter } from './reschedule-schedule.js';
// Reminder management tools
import { listRemindersRouter } from './list-reminders.js';
import { editReminderRouter } from './edit-reminder.js';
import { pauseReminderRouter } from './pause-reminder.js';
import { resumeReminderRouter } from './resume-reminder.js';
import { snoozeReminderRouter } from './snooze-reminder.js';
import { cancelReminderRouter } from './cancel-reminder.js';
import { requireInternalSecret } from '../../middleware/auth.js';

export const toolsRouter = Router();

toolsRouter.use(requireInternalSecret);

toolsRouter.use('/set_reminder', setReminderRouter);
toolsRouter.use('/schedule_call', scheduleCallRouter);
toolsRouter.use('/skip_schedule', skipScheduleRouter);
toolsRouter.use('/snooze_schedule', snoozeScheduleRouter);
toolsRouter.use('/reschedule_schedule', rescheduleScheduleRouter);
toolsRouter.use('/opt_out', optOutRouter);
toolsRouter.use('/forget_memory', forgetMemoryRouter);
toolsRouter.use('/mark_private', markPrivateRouter);
toolsRouter.use('/store_memory', storeMemoryRouter);
toolsRouter.use('/update_memory', updateMemoryRouter);
toolsRouter.use('/exclude_topic', excludeTopicRouter);
toolsRouter.use('/include_topic', includeTopicRouter);
toolsRouter.use('/list_topic_exclusions', listExclusionsRouter);
toolsRouter.use('/review_memories', reviewMemoriesRouter);
toolsRouter.use('/', voiceConsentRouter);
toolsRouter.use('/safety_event', safetyEventRouter);
toolsRouter.use('/overage_action', overageActionRouter);
toolsRouter.use('/request_upgrade', requestUpgradeRouter);
toolsRouter.use('/report_conversation_language', reportConversationLanguageRouter);
toolsRouter.use('/log_call_insights', logCallInsightsRouter);
toolsRouter.use('/set_pause_mode', setPauseModeRouter);
toolsRouter.use('/mark_topic_private', markTopicPrivateRouter);
toolsRouter.use('/store_call_preview', storeCallPreviewRouter);
toolsRouter.use('/mark_preview_outcome', markPreviewOutcomeRouter);
toolsRouter.use('/log_segment_engagement', logSegmentEngagementRouter);
toolsRouter.use('/manage_story_arc', manageStoryArcRouter);
toolsRouter.use('/store_life_chapter', storeLifeChapterRouter);
toolsRouter.use('/log_mood_snapshot', logMoodSnapshotRouter);
toolsRouter.use('/update_content_preference', updateContentPreferenceRouter);
toolsRouter.use('/update_relationship', updateRelationshipRouter);
toolsRouter.use('/mark_relationship_deceased', markRelationshipDeceasedRouter);
toolsRouter.use('/log_cognitive_observation', logCognitiveObservationRouter);
toolsRouter.use('/adjust_accessibility', adjustAccessibilityRouter);
toolsRouter.use('/store_milestone', storeMilestoneRouter);
toolsRouter.use('/mark_milestone_celebrated', markMilestoneCelebratedRouter);
toolsRouter.use('/log_health_mention', logHealthMentionRouter);
// Reminder management routes
toolsRouter.use('/list_reminders', listRemindersRouter);
toolsRouter.use('/edit_reminder', editReminderRouter);
toolsRouter.use('/pause_reminder', pauseReminderRouter);
toolsRouter.use('/resume_reminder', resumeReminderRouter);
toolsRouter.use('/snooze_reminder', snoozeReminderRouter);
toolsRouter.use('/cancel_reminder', cancelReminderRouter);
