import crypto from 'crypto';
import { NextResponse } from 'next/server';
import sendEmail from '~/core/email/send-email';
import getSupabaseServerComponentClient from '~/core/supabase/server-component-client';
import renderWeeklySummaryEmail from '~/lib/emails/weekly-summary';
import type { WeeklySummaryData } from '~/lib/ultaura/types';
import { buildNotificationRecipientToken } from '~/lib/ultaura/notification-tokens';

function validateWebhookSecret(request: Request): NextResponse | null {
  const expectedSecret = process.env.ULTAURA_INTERNAL_API_SECRET;
  const providedSecret = request.headers.get('x-webhook-secret');

  if (!expectedSecret) {
    return NextResponse.json({ error: 'Server misconfigured' }, { status: 500 });
  }

  if (!providedSecret) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const providedBuffer = Buffer.from(providedSecret, 'utf8');
  const expectedBuffer = Buffer.from(expectedSecret, 'utf8');

  if (
    providedBuffer.length !== expectedBuffer.length ||
    !crypto.timingSafeEqual(providedBuffer, expectedBuffer)
  ) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  return null;
}

function formatTrend(value: number | null, unit?: string): string {
  if (value === null) return '';
  const sign = value > 0 ? `+${value}` : `${value}`;
  return ` (${sign}${unit ?? ''} vs last week)`;
}

function buildTextSummary(
  summary: WeeklySummaryData,
  options?: { isSelfRecipient?: boolean; unsubscribeLink?: string }
): string {
  const avgDurationLabel =
    summary.avgDurationMinutes === null ? 'N/A' : `${summary.avgDurationMinutes}m`;
  const durationTrendLabel =
    summary.avgDurationMinutes === null ? '' : formatTrend(summary.durationTrendValue, 'm');
  const effectiveTier = options?.isSelfRecipient
    ? 'tier_4'
    : summary.sharingTier || 'tier_1';
  const allowMood = options?.isSelfRecipient || effectiveTier !== 'tier_1';
  const allowTopics = options?.isSelfRecipient || effectiveTier === 'tier_3' || effectiveTier === 'tier_4';
  const allowConcerns = options?.isSelfRecipient || effectiveTier === 'tier_4';
  const headline = options?.isSelfRecipient
    ? 'Weekly Check-in Summary'
    : `Weekly Check-in Summary for ${summary.lineName}`;
  const lines: Array<string | null> = [
    headline,
    `Week of ${summary.weekStartDate} to ${summary.weekEndDate}`,
    '',
    `Calls answered: ${summary.answeredCalls}/${summary.scheduledCalls} scheduled${formatTrend(summary.answerTrendValue)}`,
    `Average duration: ${avgDurationLabel}${durationTrendLabel}`,
    summary.showMissedCallsWarning ? `Missed calls: ${summary.missedCalls}` : null,
    allowMood && summary.engagementNote ? `Engagement: ${summary.engagementNote}` : null,
    allowMood && summary.moodSummary ? `Mood: ${summary.moodSummary}` : null,
    allowMood && summary.moodShiftNote ? `Mood pattern: ${summary.moodShiftNote}` : null,
    allowConcerns && summary.socialNeedNote ? summary.socialNeedNote : null,
    allowTopics && summary.topTopics.length > 0
      ? `Topics: ${summary.topTopics.map((topic) => topic.label).join(', ')}`
      : null,
    allowConcerns && summary.concerns.length > 0
      ? `Wellbeing notes: ${summary.concerns
          .map((concern) => {
            const novelty = concern.novelty[0].toUpperCase() + concern.novelty.slice(1);
            const severity =
              concern.novelty === 'resolved'
                ? ` (was ${concern.severity})`
                : ` (${concern.severity})`;
            return `${novelty}: ${concern.label}${severity}`;
          })
          .join('; ')}`
      : null,
    allowConcerns && summary.needsFollowUp
      ? `Follow-up suggested: ${summary.followUpReasons.join(', ')}`
      : null,
    summary.safetyEvents.length > 0
      ? `Safety alerts: ${summary.safetyEvents
          .map((event) => {
            const action = event.actionTaken ? ` (${event.actionTaken})` : '';
            return `${event.severity} alert${action}`;
          })
          .join('; ')}`
      : null,
    `Usage: ${summary.usageSummary.minutesUsed} min used, ${summary.usageSummary.minutesRemaining} min remaining` +
      (summary.usageSummary.overageMinutes > 0
        ? `, ${summary.usageSummary.overageMinutes} min over ($${summary.usageSummary.overageCost.toFixed(2)})`
        : ''),
    '',
    'These insights are generated by AI based on conversation patterns and are not medical, clinical, or professional advice. Ultaura is not an emergency service. If you believe there is immediate danger, contact local emergency services (911 in the US).',
    '',
    `Manage notification preferences: ${summary.settingsUrl}`,
    options?.unsubscribeLink ? `Unsubscribe: ${options.unsubscribeLink}` : null,
  ];

  return lines.filter(Boolean).join('\n');
}

function getSiteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, '');
}

export async function POST(request: Request) {
  const unauthorizedResponse = validateWebhookSecret(request);
  if (unauthorizedResponse) {
    return unauthorizedResponse;
  }

  const body = await request.json().catch(() => null);
  const payload = body as { summary?: WeeklySummaryData; sharingSummary?: WeeklySummaryData | null } | WeeklySummaryData | null;
  const summary = payload && 'summary' in payload ? payload.summary || null : (payload as WeeklySummaryData | null);
  const sharingSummary = payload && 'summary' in payload ? (payload.sharingSummary ?? null) : null;

  if (!summary?.accountId || !summary?.lineName || !summary?.settingsUrl) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
  }

  const emailFrom = process.env.EMAIL_SENDER;
  if (!emailFrom) {
    return NextResponse.json({ error: 'Missing EMAIL_SENDER configuration' }, { status: 500 });
  }

  const supabase = getSupabaseServerComponentClient({ admin: true });
  const { data: account, error: accountError } = await supabase
    .from('ultaura_accounts')
    .select('billing_email, user_type, sharing_enabled')
    .eq('id', summary.accountId)
    .single();

  if (accountError || !account?.billing_email) {
    return NextResponse.json({ error: 'Missing billing email' }, { status: 400 });
  }

  const { data: voiceConsent } = await supabase
    .from('ultaura_line_voice_consent')
    .select('sharing_consent, sharing_tier')
    .eq('line_id', summary.lineId)
    .maybeSingle();

  const sharingConsent = voiceConsent?.sharing_consent ?? 'pending';
  const sharingTier = (voiceConsent?.sharing_tier ?? 'tier_1') as
    | 'tier_1'
    | 'tier_2'
    | 'tier_3'
    | 'tier_4';
  const sharingPayload = sharingSummary ?? { ...summary, sharingTier };

  try {
    const recipients = new Map<string, { isPrimary: boolean; token?: string }>();

    recipients.set(account.billing_email, { isPrimary: true });

    const allowFamilyRecipients = account.user_type === 'family_managed' ||
      (account.user_type === 'self' && account.sharing_enabled && sharingConsent === 'granted');

    if (allowFamilyRecipients) {
      const { data: recipientRows, error: recipientError } = await supabase
        .from('ultaura_notification_recipients')
        .select('id, email')
        .eq('account_id', summary.accountId)
        .not('confirmed_at', 'is', null)
        .is('unsubscribed_at', null);

      if (recipientError) {
        return NextResponse.json({ error: 'Failed to load recipients' }, { status: 500 });
      }

      for (const recipient of recipientRows || []) {
        if (!recipients.has(recipient.email)) {
          recipients.set(recipient.email, {
            isPrimary: false,
            token: buildNotificationRecipientToken(recipient.id),
          });
        }
      }
    }

    const subject = `Weekly Check-in Summary for ${summary.lineName}`;

    for (const [email, meta] of Array.from(recipients.entries())) {
      const unsubscribeLink = meta.isPrimary || !meta.token
        ? undefined
        : `${getSiteUrl()}/api/ultaura/unsubscribe/${meta.token}`;
      const isSelfRecipient = account.user_type === 'self' && meta.isPrimary;
      const summaryForRecipient = isSelfRecipient ? summary : {
        ...sharingPayload,
        sharingTier: sharingPayload.sharingTier ?? sharingTier,
      };

      const html = renderWeeklySummaryEmail({
        ...summaryForRecipient,
        billingEmail: email,
        isSelfRecipient,
        isPrimaryRecipient: meta.isPrimary,
        unsubscribeLink,
      });
      const text = buildTextSummary(summaryForRecipient, { isSelfRecipient, unsubscribeLink });
      const headers = unsubscribeLink
        ? {
            'List-Unsubscribe': `<${unsubscribeLink}>`,
            'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
          }
        : undefined;

      await sendEmail({
        from: emailFrom,
        to: email,
        subject,
        html,
        text,
        headers,
      });
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to send weekly summary email' }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}
