import {
  Body,
  Container,
  Head,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Tailwind,
  Text,
} from '@react-email/components';
import React from 'react';

import { brandColors } from '~/lib/brand-colors';

interface EmailLayoutProps {
  preview: string;
  children: React.ReactNode;
  signOff?: string; // Default: '- The Ultaura Team'
  footerLinks?: Array<{ label: string; href: string }>;
  aiDisclaimer?: boolean;
  baseUrl?: string;
}

export function EmailLayout({
  preview,
  children,
  signOff = '- The Ultaura Team',
  footerLinks,
  aiDisclaimer = false,
  baseUrl,
}: EmailLayoutProps) {
  const siteUrl = baseUrl || process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
  const normalizedSiteUrl = siteUrl.replace(/\/$/, '');
  const logoUrl = `${normalizedSiteUrl}/logos/logo-email.png`;

  return (
    <Html>
      <Head>
        <meta name="color-scheme" content="light" />
        <meta name="supported-color-schemes" content="light" />
        <style
          dangerouslySetInnerHTML={{
            __html: `@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');`,
          }}
        />
      </Head>
      <Preview>{preview}</Preview>

      <Tailwind>
        <Body
          className="bg-stone-50 my-auto mx-auto"
          style={{
            fontFamily:
              "Manrope, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
          }}
        >
          <Container
            className="rounded-lg my-[32px] mx-auto p-[24px] bg-white"
            style={{
              maxWidth: '560px',
              width: '100%',
              border: `1px solid ${brandColors.border}`,
            }}
          >
            <Section className="mt-[4px] mb-[16px]">
              <table
                cellPadding="0"
                cellSpacing="0"
                role="presentation"
                style={{ border: 'none' }}
              >
                <tr>
                  <td style={{ verticalAlign: 'middle', paddingRight: '10px' }}>
                    <Img
                      src={logoUrl}
                      width="36"
                      height="36"
                      alt="Ultaura"
                      style={{ display: 'block' }}
                    />
                  </td>
                  <td style={{ verticalAlign: 'middle' }}>
                    <Text
                      className="m-0 text-[18px] font-semibold"
                      style={{
                        color: brandColors.primary,
                        lineHeight: '1',
                        letterSpacing: '-0.01em',
                      }}
                    >
                      Ultaura
                    </Text>
                  </td>
                </tr>
              </table>
            </Section>

            {children}

            <Text className="text-[14px] text-stone-700 mt-[18px] mb-0">
              {signOff}
            </Text>

            <Hr
              className="my-[20px] mx-0 w-full"
              style={{ borderColor: brandColors.border }}
            />

            {aiDisclaimer && (
              <Text className="text-[12px] text-stone-500 m-0 text-center">
                These insights are generated by AI based on conversation
                patterns and are not medical, clinical, or professional advice.
                Ultaura is not an emergency service. If you believe there is
                immediate danger, contact local emergency services (911 in the
                US).
              </Text>
            )}

            <Text className="text-[12px] text-stone-500 mt-[8px] mb-0 text-center">
              Companionship, one call at a time.
            </Text>

            {footerLinks?.length ? (
              <Text className="text-[12px] text-stone-500 mt-[8px] mb-0 text-center">
                {footerLinks.map((link, index) => (
                  <span key={link.href}>
                    {index > 0 && ' | '}
                    <Link
                      href={link.href}
                      style={{ color: brandColors.primary }}
                    >
                      {link.label}
                    </Link>
                  </span>
                ))}
              </Text>
            ) : null}
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
