'use client';

import Link from 'next/link';
import { History, Info, Phone, Share2 } from 'lucide-react';
import type { InsightsDashboard, CallSessionRow } from '~/lib/ultaura/types';
import { InfoTip } from '~/core/ui/InfoTip';
import { InsightsSummary } from '../../components/InsightsSummary';
import { CallMetrics } from '../../components/CallMetrics';
import { CallActivityList } from '../../../lines/[lineId]/components/CallActivityList';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '~/core/ui/Accordion';
import { SHARING_TIER_LABELS, type TierAccess } from './shared';

const SHARING_TIER_ORDER = ['tier_1', 'tier_2', 'tier_3', 'tier_4'] as const;

interface OverviewTabContentProps {
  dashboard: InsightsDashboard | null;
  tierAccess: TierAccess;
}

export function OverviewTabContent({ dashboard, tierAccess }: OverviewTabContentProps) {
  const { isFamilyManaged, effectiveTier, allowMood, lineName } = tierAccess;

  // Active tier: self-managed = tier_4 (full access), family-managed = effectiveTier or tier_1
  const activeTier = !isFamilyManaged
    ? 'tier_4'
    : effectiveTier ?? 'tier_1';
  const sharingConsentNote =
    isFamilyManaged && dashboard?.sharingConsent !== 'granted'
      ? ` (not enabled by ${lineName})`
      : '';

  return (
    <div className="space-y-6">
      <p className="text-sm text-muted-foreground">
        Weekly insights and call activity patterns at a glance.
      </p>
      {/* AI Disclaimer - always shown */}
      <div className="flex items-start gap-3 rounded-lg border border-primary/30 bg-primary/5 px-4 py-3.5">
        <Info className="h-[18px] w-[18px] text-primary flex-shrink-0 mt-0.5" />
        <p className="text-xs text-primary leading-snug">
          These insights are generated by AI based on conversation patterns and are not
          medical, clinical, or professional advice. Ultaura is not an emergency service. If
          you believe there is immediate danger, contact local emergency services (911 in the
          US).{' '}
          <Link
            href="/docs/insights-and-reports"
            className="text-primary font-medium underline underline-offset-2 hover:no-underline"
          >
            Learn more →
          </Link>
        </p>
      </div>

      {/* Dashboard sections - only when dashboard is available */}
      {dashboard && (
        <>
          {!dashboard.insightsEnabled && (
            <div className="rounded-lg border border-border bg-muted/40 p-4">
              <p className="text-sm text-foreground">
                Insights are disabled for this line. Historical insights remain visible.
              </p>
              <Link
                href={`/dashboard/lines/${dashboard.lineShortId}/settings`}
                className="text-sm text-primary hover:underline"
              >
                Enable insights in Line Settings
              </Link>
            </div>
          )}

          {/* Sharing Level - always shown */}
          <div className="rounded-xl bg-card p-6">
            <div className="flex items-center gap-2 mb-5">
              <Share2 className="w-4 h-4 text-muted-foreground" />
              <h3 className="text-sm font-semibold text-foreground">Sharing Level</h3>
              <InfoTip
                content={
                  isFamilyManaged
                    ? 'Your loved one sets this during their calls with Ultaura—not from this dashboard.'
                    : 'You set this during your calls with Ultaura.'
                }
              />
            </div>
            <div className="mt-3 -ml-1 flex flex-wrap gap-2">
              {SHARING_TIER_ORDER.map((tier) => {
                const isActive = tier === activeTier;
                return (
                  <span
                    key={tier}
                    className={`inline-flex rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
                      isActive
                        ? 'bg-primary/10 text-primary ring-1 ring-primary/30'
                        : 'bg-muted/60 text-muted-foreground'
                    }`}
                  >
                    {SHARING_TIER_LABELS[tier]}
                  </span>
                );
              })}
            </div>
            {sharingConsentNote ? (
              <p className="mt-1 text-xs text-muted-foreground">{sharingConsentNote}</p>
            ) : null}
          </div>

          <InsightsSummary summary={dashboard.summary} showMood={allowMood} />
          <CallMetrics activity={dashboard.callActivity} />

          {/* Call History - collapsible */}
          <Accordion>
            <AccordionItem value="call-history">
              <AccordionTrigger>
                <div className="flex items-center gap-2">
                  <History className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-semibold text-foreground">Call History</span>
                  <InfoTip content="A complete list of all calls made and received over the past 30 days, including call duration and outcome." />
                </div>
              </AccordionTrigger>
              <AccordionContent>
                <CallActivityList sessions={dashboard.callHistory} />
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </>
      )}

      {/* Fallback when no dashboard */}
      {!dashboard && (
        <div className="rounded-xl border border-border bg-card p-6">
          <p className="text-sm text-muted-foreground">
            No insights data available yet. Insights will appear after the first few calls.
          </p>
        </div>
      )}
    </div>
  );
}
