'use client';

import Link from 'next/link';
import { Info } from 'lucide-react';
import type { InsightsDashboard, CallSessionRow } from '~/lib/ultaura/types';
import { InsightsSummary } from '../../components/InsightsSummary';
import { CallMetrics } from '../../components/CallMetrics';
import { RetentionInsightsCard } from '../../components/RetentionInsightsCard';
import { CallActivityList } from '../../../lines/[lineId]/components/CallActivityList';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '~/core/ui/Accordion';
import { SHARING_TIER_LABELS, type TierAccess } from './shared';

interface OverviewTabContentProps {
  dashboard: InsightsDashboard | null;
  tierAccess: TierAccess;
}

export function OverviewTabContent({ dashboard, tierAccess }: OverviewTabContentProps) {
  const { isFamilyManaged, effectiveTier, allowMood, lineName } = tierAccess;

  // Compute sharing display label
  const sharingDisplayLabel = !isFamilyManaged
    ? 'Full Access (Self-managed)'
    : effectiveTier
      ? SHARING_TIER_LABELS[effectiveTier]
      : SHARING_TIER_LABELS['tier_1'];
  const sharingConsentNote =
    isFamilyManaged && dashboard?.sharingConsent !== 'granted'
      ? ` (not enabled by ${lineName})`
      : '';

  return (
    <div className="space-y-6">
      {/* AI Disclaimer - always shown */}
      <div className="flex items-start gap-3 rounded-lg border border-primary/30 bg-primary/5 px-4 py-3.5">
        <Info className="h-[18px] w-[18px] text-primary flex-shrink-0 mt-0.5" />
        <p className="text-xs text-primary leading-snug">
          These insights are generated by AI based on conversation patterns and are not
          medical, clinical, or professional advice. Ultaura is not an emergency service. If
          you believe there is immediate danger, contact local emergency services (911 in the
          US).
        </p>
      </div>

      {/* Dashboard sections - only when dashboard is available */}
      {dashboard && (
        <>
          {!dashboard.insightsEnabled && (
            <div className="rounded-lg border border-border bg-muted/40 p-4">
              <p className="text-sm text-foreground">
                Insights are disabled for this line. Historical insights remain visible.
              </p>
              <Link
                href={`/dashboard/lines/${dashboard.lineShortId}/settings`}
                className="text-sm text-primary hover:underline"
              >
                Enable insights in Line Settings
              </Link>
            </div>
          )}

          {/* Sharing Level - always shown */}
          <div className="rounded-lg border border-border bg-muted/40 p-4">
            <div className="text-sm font-medium text-foreground">Sharing level</div>
            <p className="text-sm text-muted-foreground mt-1">
              {sharingDisplayLabel}{sharingConsentNote}
            </p>
          </div>

          {/* Summary + Call Activity */}
          <div className="grid gap-6 lg:grid-cols-2">
            <InsightsSummary summary={dashboard.summary} showMood={allowMood} />
            <CallMetrics activity={dashboard.callActivity} />
          </div>

          {/* Call History - collapsible */}
          <Accordion>
            <AccordionItem value="call-history">
              <AccordionTrigger>Call History</AccordionTrigger>
              <AccordionContent>
                <CallActivityList sessions={dashboard.callHistory} />
              </AccordionContent>
            </AccordionItem>
          </Accordion>

          {/* Retention Highlights */}
          <RetentionInsightsCard retention={dashboard.retention} />
        </>
      )}

      {/* Fallback when no dashboard */}
      {!dashboard && (
        <div className="rounded-xl border border-border bg-card p-6">
          <p className="text-sm text-muted-foreground">
            No insights data available yet. Insights will appear after the first few calls.
          </p>
        </div>
      )}
    </div>
  );
}
