export const SAFETY_EXCLUSION_PATTERNS = [
  // Common false positives
  'killing time',
  'kill for a',
  'killing it',
  'drop dead gorgeous',
  'to die for',
  'dying to',
  'dead tired',
  'dead serious',
  'bored to death',
  'scared to death',
  'hurt feelings',
  'hurt my back',
  'hurt my knee',
  'hurt my leg',
  'hurt my arm',
  // Context exclusions (talking about others/media)
  'movie about',
  'book about',
  'article about',
  'news about',
  'show about',
  'heard about someone',
  'my friend',
  'my neighbor',
  'their friend',
  'his friend',
  'her friend',
] as const;
