import { Metadata } from 'next';
import AppHeader from '../../../components/AppHeader';
import { PageTitleWithInfo } from '~/core/ui/PageTitleWithInfo';
import { PageBody } from '~/core/ui/Page';
import { getInsightsDashboard } from '~/lib/ultaura/insights';
import {
  getCallPreviewHistory,
  getSegmentEngagementStats,
  getStoryArcProgress,
} from '~/lib/ultaura/retention';
import { TrialExpiredBanner } from '~/components/ultaura/TrialExpiredBanner';
import { TrialStatusBadge } from '~/components/ultaura/TrialStatusBadge';
import { InsightsPageHeader } from '../components/InsightsPageHeader';
import { EngagementTabContent } from '../components/EngagementTabContent';
import Button from '~/core/ui/Button';
import { computeTierAccess } from '../components/tier-utils';
import { loadInsightsPageData } from '../loader';

export const metadata: Metadata = {
  title: 'Engagement - Insights - Ultaura',
};

interface PageProps {
  params: Promise<{
    lineId: string;
  }>;
}

export default async function InsightsEngagementPage({ params }: PageProps) {
  const { lineId } = await params;
  const loaderResult = await loadInsightsPageData(lineId);

  if (!loaderResult) {
    return (
      <>
        <AppHeader title="Insights" description="Weekly insights without transcripts" />
        <PageBody>
          <div className="max-w-lg mx-auto text-center py-8">
            <h2 className="text-2xl font-semibold mb-4">Get Started with Ultaura</h2>
            <p className="text-muted-foreground mb-6">
              Start a 14-day free trial to unlock insights and weekly summaries.
            </p>
            <Button variant="default" href="/dashboard/settings/subscription">
              Start 14-day free trial
            </Button>
          </div>
        </PageBody>
      </>
    );
  }

  const {
    lines,
    selectedLine,
    trialInfo,
    isTrialExpired,
    isTrialActive,
    trialPlanName,
  } = loaderResult;

  // Fetch data needed for Engagement tab
  const [dashboard, callPreviews, storyArcs, segmentStats] = await Promise.all([
    getInsightsDashboard(selectedLine.id),
    getCallPreviewHistory(selectedLine.id, 10),
    getStoryArcProgress(selectedLine.id),
    getSegmentEngagementStats(selectedLine.id),
  ]);

  // Compute tier access
  const tierAccess = computeTierAccess(
    dashboard?.userType,
    dashboard?.sharingConsent,
    dashboard?.sharingTier,
    dashboard?.lineName ?? selectedLine.display_name
  );

  return (
    <>
      <AppHeader
        title={
          <PageTitleWithInfo title="Insights" storageKey="insights_info_tip_collapsed" infoLabel="Insights disclaimer">
            These insights are generated by AI based on conversation patterns and are not
            medical, clinical, or professional advice. Ultaura is not an emergency service. If
            you believe there is immediate danger, contact local emergency services (911 in the
            US).{' '}
            <a href="/docs/insights-and-reports" className="font-medium text-primary underline underline-offset-2 hover:no-underline">
              Learn more →
            </a>
          </PageTitleWithInfo>
        }
        description="Weekly insights without transcripts"
      >
        {isTrialActive && trialInfo ? (
          <TrialStatusBadge daysRemaining={trialInfo.daysRemaining} planName={trialPlanName} />
        ) : null}
      </AppHeader>
      <PageBody>
        <div className="space-y-6 pb-12">
          {isTrialExpired && <TrialExpiredBanner trialPlanName={trialPlanName} />}

          <InsightsPageHeader
            lines={lines}
            currentLineShortId={selectedLine.short_id}
          />

          <EngagementTabContent
            dashboard={dashboard}
            callPreviews={callPreviews}
            storyArcs={storyArcs}
            segmentStats={segmentStats}
            timezone={selectedLine.timezone}
            tierAccess={tierAccess}
          />
        </div>
      </PageBody>
    </>
  );
}
